module.exports = [
  // ======================== 서울 ========================

  // 서울대학교
  {
    name: '서울대학교',
    department: '디자인학부',
    region: '서울',
    admissionTypes: ['정시'],
    applicationPeriod: '2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['디자인 창작'],
    recruitCount: '정시 약 30명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 나군. 수능60%+실기40%. 디자인 창작 4시간.',
    practiceGuide: {
      overview: '주어진 주제와 조건을 바탕으로 창의적 디자인 결과물을 완성하는 시험이다. 발상력과 조형 완성도 모두 중요하다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '재료 제한 없음 (지참)' },
      trends: [
        { year: '2025', topic: '환경·지속가능성 관련 디자인 창작' },
        { year: '2024', topic: '사회 현상 반영 시각 표현' },
      ],
      scoring: [
        { item: '창의성', detail: '주제 해석의 독창성과 발상의 참신함' },
        { item: '조형성', detail: '색채·형태·구성의 완성도' },
        { item: '디자인 적합성', detail: '디자인 목적에 부합하는 표현 여부' },
      ],
      strategy: ['주제를 다양한 관점으로 해석하는 연습을 충분히 쌓는다.', '4시간 내 완성도를 높이는 시간 배분 훈련이 필수다.'],
      cautions: ['단순 장식적 표현보다 개념 기반 조형 전개를 보여줘야 한다.'],
    },
  },
  {
    name: '서울대학교',
    department: '서양화과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공실기 (서양화)'],
    recruitCount: '수시 약 7명 / 정시 약 5명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 나군, 수능60%+실기40%, 실기 6시간. 수시는 학종(포트폴리오+면접), 실기 없음.',
    practiceGuide: {
      overview: '정시 실기는 6시간 동안 서양화 전공 표현 능력을 평가한다. 수시는 포트폴리오와 면접으로만 선발한다.',
      examInfo: { time: '6시간', paper: '지정 용지', materials: '유화 또는 수채화 (공고 확인)' },
      trends: [
        { year: '2025', topic: '인물 또는 정물 혼합 구성' },
        { year: '2024', topic: '공간감과 빛 표현 중심' },
      ],
      scoring: [
        { item: '표현력', detail: '매체 특성을 살린 회화적 표현' },
        { item: '구성력', detail: '화면 구성과 공간감' },
        { item: '묘사력', detail: '대상의 형태 및 질감 재현' },
      ],
      strategy: ['장시간 실기에 맞춰 완성도와 체력을 함께 훈련한다.', '수시 지원 시 포트폴리오의 작품 다양성과 완성도를 우선한다.'],
      cautions: ['정시와 수시 전형 방식이 완전히 달라 전략을 분리해 준비해야 한다.'],
    },
  },
  {
    name: '서울대학교',
    department: '동양화과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공실기 (동양화)'],
    recruitCount: '수시 약 5명 / 정시 약 4명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 나군, 수능60%+실기40%, 실기 6시간. 수시는 학종(포트폴리오+면접), 실기 없음.',
    practiceGuide: {
      overview: '동양화 매체(먹, 채색 등)를 활용한 표현 능력을 평가한다. 수시는 포트폴리오와 면접으로 선발한다.',
      examInfo: { time: '6시간', paper: '한지 또는 지정 용지', materials: '먹, 채색 등 동양화 재료' },
      trends: [
        { year: '2025', topic: '자연물 또는 정물 동양화 표현' },
        { year: '2024', topic: '공간·여백 활용 구성' },
      ],
      scoring: [
        { item: '매체 활용', detail: '동양화 재료의 특성을 이해하고 구사하는 능력' },
        { item: '조형성', detail: '구도와 여백 처리의 완성도' },
        { item: '표현력', detail: '선과 면의 동양화적 표현' },
      ],
      strategy: ['동양화 고유 재료(먹, 채색)를 능숙하게 다룰 수 있도록 꾸준히 연습한다.', '수시 포트폴리오는 전통과 현대 감각을 균형 있게 담는다.'],
      cautions: ['서양화 기법 위주 훈련보다 동양화 특유의 조형 언어를 익히는 것이 중요하다.'],
    },
  },
  {
    name: '서울대학교',
    department: '조소과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공실기 (조소)'],
    recruitCount: '수시 약 5명 / 정시 약 4명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 나군, 수능60%+실기40%, 실기 6시간. 수시는 학종(포트폴리오+면접), 실기 없음.',
    practiceGuide: {
      overview: '입체 조형 능력과 재료 다루는 기술을 평가한다. 수시는 포트폴리오와 면접으로 선발한다.',
      examInfo: { time: '6시간', paper: '해당 없음', materials: '점토 등 조소 재료 (공고 확인)' },
      trends: [
        { year: '2025', topic: '인체 또는 추상 입체 표현' },
        { year: '2024', topic: '공간성과 재료 특성 중심 조형' },
      ],
      scoring: [
        { item: '입체 조형력', detail: '3차원 형태 구성과 균형' },
        { item: '재료 이해', detail: '조소 재료 특성 활용 능력' },
        { item: '창의성', detail: '독창적 개념 표현' },
      ],
      strategy: ['다양한 재료로 입체 표현 훈련을 반복한다.', '수시 포트폴리오는 평면과 입체 작품을 고루 포함한다.'],
      cautions: ['6시간 내 완성도 있는 결과물을 만들기 위해 작업 시간 관리를 체계적으로 훈련해야 한다.'],
    },
  },

  // 이화여자대학교
  {
    name: '이화여자대학교',
    department: '디자인학부',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['주제에 의한 사고와 표현'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능60%+실기40%. 켄트지 2절, "주제에 의한 사고와 표현" 실기.',
    practiceGuide: {
      overview: '주어진 주제를 자유롭게 해석하여 사고 과정과 표현력을 함께 보여주는 시험이다. 켄트지 2절 규격을 사용한다.',
      examInfo: { time: '4시간', paper: '켄트지 2절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '사회적 메시지를 시각화하는 주제' },
        { year: '2024', topic: '일상 사물의 재해석' },
      ],
      scoring: [
        { item: '사고력', detail: '주제 해석의 논리성과 독창성' },
        { item: '표현력', detail: '시각 언어로 아이디어를 구현하는 능력' },
        { item: '완성도', detail: '화면 전체의 조형적 완성도' },
      ],
      strategy: ['주제 해석의 다양한 관점을 연습하고 시각화 훈련을 반복한다.', '2절 화면을 효과적으로 구성하는 레이아웃 감각을 기른다.'],
      cautions: ['단순 묘사보다 주제에 대한 사고 흐름이 드러나야 고득점이 가능하다.'],
    },
  },
  {
    name: '이화여자대학교',
    department: '조형예술학부',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공별 실기'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능60%+실기40%. 회화·조소 등 전공별 실기 시험.',
    practiceGuide: {
      overview: '조형예술 전공 특성에 맞는 표현 능력을 평가한다. 전공(회화, 조소 등)에 따라 실기 내용이 다르다.',
      examInfo: { time: '4~6시간 (전공별)', paper: '지정 용지', materials: '전공별 상이 (공고 확인)' },
      trends: [
        { year: '2025', topic: '전공별 개성 있는 표현 과제' },
        { year: '2024', topic: '관찰 기반 조형 표현' },
      ],
      scoring: [
        { item: '전공 적합성', detail: '전공 표현 매체와 기법의 이해도' },
        { item: '조형성', detail: '구성·색채·형태의 완성도' },
        { item: '개성', detail: '독창적 표현 관점' },
      ],
      strategy: ['지원 전공의 실기 유형을 정확히 파악하고 집중 훈련한다.', '기출 경향을 분석해 반복 출제 유형을 대비한다.'],
      cautions: ['전공별 실기 방식이 달라 반드시 해당 전공 모집요강을 확인해야 한다.'],
    },
  },

  // 중앙대학교
  {
    name: '중앙대학교',
    department: '디자인학부',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 50명 / 정시 약 25명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 기초디자인 실기.',
    practiceGuide: {
      overview: '제시된 오브제와 주제어를 활용해 기초디자인 화면을 구성하는 시험이다. 실기 비중이 60%로 높다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '인공 오브제 + 자연 요소 조합' },
        { year: '2024', topic: '단일 오브제 반복 구성' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 창의성과 주제 연결력' },
        { item: '구성', detail: '화면 구성의 조화와 시각적 흐름' },
        { item: '표현', detail: '채색 기술과 질감 표현의 완성도' },
      ],
      strategy: ['다양한 오브제를 활용한 기초디자인 화면 구성을 반복 연습한다.', '실기 비중이 높으므로 실기 완성도에 집중해 전략을 세운다.'],
      cautions: ['수능 점수가 낮아도 실기로 역전이 가능하지만 기초디자인 수준이 매우 높아야 한다.'],
    },
  },
  {
    name: '중앙대학교',
    department: '공예학과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '소묘'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 기초디자인 또는 소묘 선택.',
    practiceGuide: {
      overview: '기초디자인과 소묘 중 선택하여 응시하는 실기 시험이다. 공예 전공 특성에 맞는 표현 능력을 본다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 실기에 따른 재료 지참' },
      trends: [
        { year: '2025', topic: '공예적 오브제 기초디자인 또는 정밀 소묘' },
        { year: '2024', topic: '재료 질감 표현 중심 구성' },
      ],
      scoring: [
        { item: '실기 유형 이해', detail: '선택 실기 방식에 맞는 표현' },
        { item: '조형성', detail: '형태·질감·구성의 완성도' },
        { item: '완성도', detail: '전체 화면의 마무리 수준' },
      ],
      strategy: ['기초디자인과 소묘 중 자신에게 유리한 과목을 선택해 집중 준비한다.', '공예 특유의 재료·질감 표현에 강점을 둔 화면을 연습한다.'],
      cautions: ['선택 과목에 따라 필요한 재료와 연습 방향이 달라지므로 조기에 결정해야 한다.'],
    },
  },

  // 한양대학교
  {
    name: '한양대학교',
    department: '디자인학부 (통합모집)',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '정시 수능50%+실기50%. 3절지 5시간, 주제어 30개 중 2개 추첨.',
    practiceGuide: {
      overview: '30개 주제어 중 2개를 현장 추첨하여 기초디자인 화면을 완성하는 시험이다. 3절지에 5시간이 주어진다.',
      examInfo: { time: '5시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '추상 개념어 + 구체 사물 조합' },
        { year: '2024', topic: '일상 오브제 + 감각적 주제어 구성' },
      ],
      scoring: [
        { item: '발상', detail: '추첨 주제어 2개를 연결하는 창의적 해석' },
        { item: '구성', detail: '3절 화면의 레이아웃과 시각적 완성도' },
        { item: '표현', detail: '채색 기술과 오브제 묘사력' },
      ],
      strategy: ['30개 주제어를 모두 연습해 어떤 조합이 나와도 빠르게 아이디어를 도출할 수 있도록 준비한다.', '5시간 실기에 맞는 시간 배분 전략을 사전에 세운다.'],
      cautions: ['현장 추첨이므로 특정 주제에만 편중된 준비는 위험하다.'],
    },
  },

  // 경희대학교
  {
    name: '경희대학교',
    department: '미술학부 (서양화/한국화/조각)',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공별 실기'],
    recruitCount: '수시 약 20명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 서양화·한국화·조각 전공별 실기.',
    practiceGuide: {
      overview: '전공별로 다른 실기 과제를 통해 기초 표현 능력과 전공 적합성을 평가한다. 실기 비중이 60%다.',
      examInfo: { time: '4~6시간 (전공별)', paper: '지정 용지', materials: '전공별 상이' },
      trends: [
        { year: '2025', topic: '인물·정물·자연물 전공별 표현' },
        { year: '2024', topic: '관찰 및 상상 혼합 표현' },
      ],
      scoring: [
        { item: '전공 기초', detail: '전공 매체와 기법 이해도' },
        { item: '묘사력', detail: '대상 형태와 질감 표현' },
        { item: '완성도', detail: '화면 전체 마무리 수준' },
      ],
      strategy: ['지원 전공의 실기 유형과 기출을 집중 분석한다.', '실기 비중이 높으므로 실기 준비에 더 많은 시간을 배분한다.'],
      cautions: ['전공별 실기 내용이 달라 반드시 해당 전공 공고를 확인해야 한다.'],
    },
  },
  {
    name: '경희대학교',
    department: '시각/산업/환경조경디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 기초디자인.',
    practiceGuide: {
      overview: '오브제와 주제를 활용한 기초디자인 화면 구성 능력을 평가한다. 실기 비중 60%로 실기가 당락에 큰 영향을 미친다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 소재와 추상 개념 결합 구성' },
        { year: '2024', topic: '기하 형태 활용 패턴 디자인' },
      ],
      scoring: [
        { item: '발상력', detail: '오브제와 주제 연결의 창의성' },
        { item: '화면 구성', detail: '레이아웃의 조화와 시각적 완성도' },
        { item: '채색', detail: '색채 조화와 완성도' },
      ],
      strategy: ['다양한 오브제 기초디자인 연습을 꾸준히 반복한다.', '경희대 기출 경향을 분석해 구성 방향성을 잡는다.'],
      cautions: ['경희대는 기초디자인 중에서도 세련된 색채 감각을 중요시하는 경향이 있다.'],
    },
  },

  // 숙명여자대학교
  {
    name: '숙명여자대학교',
    department: '시각·영상/산업디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 기초디자인.',
    practiceGuide: {
      overview: '오브제와 주제를 활용한 기초디자인을 평가한다. 구성력과 채색 완성도가 핵심이다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '생활용품 오브제 구성' },
        { year: '2024', topic: '자연물과 인공물 혼합 구성' },
      ],
      scoring: [
        { item: '발상', detail: '주제 해석의 참신함' },
        { item: '구성', detail: '화면 레이아웃의 완성도' },
        { item: '채색', detail: '색채 조화와 마감 수준' },
      ],
      strategy: ['숙명여대 기출 오브제 유형을 분석하고 반복 훈련한다.', '실기 비중이 높으므로 실기 완성도를 최우선으로 준비한다.'],
      cautions: ['화면이 지나치게 단조롭거나 오브제 활용이 소극적이면 낮은 점수를 받을 수 있다.'],
    },
  },
  {
    name: '숙명여자대학교',
    department: '회화과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '수채화'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 가군. 수능40%+실기60%. 소묘 또는 수채화 선택.',
    practiceGuide: {
      overview: '소묘 또는 수채화 중 선택하여 응시하는 회화 기초 실기 시험이다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 과목에 맞는 재료 지참' },
      trends: [
        { year: '2025', topic: '정물 또는 인물 관찰 표현' },
        { year: '2024', topic: '빛과 그림자 중심 묘사' },
      ],
      scoring: [
        { item: '묘사력', detail: '대상 형태 및 질감 정확한 표현' },
        { item: '톤/색감', detail: '명암 단계 또는 색채 조화' },
        { item: '완성도', detail: '전체 화면 마무리 수준' },
      ],
      strategy: ['소묘와 수채화 중 강점 있는 과목을 선택해 집중 훈련한다.', '정물·인물 등 다양한 대상을 반복 묘사 훈련한다.'],
      cautions: ['선택 과목을 늦게 결정하면 준비 시간이 부족해질 수 있어 조기에 결정해야 한다.'],
    },
  },

  // 동덕여자대학교
  {
    name: '동덕여자대학교',
    department: '시각/실내/패션디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '14.4:1',
    note: '수능40%+실기60%. 기초디자인. 경쟁률 14.4:1.',
    practiceGuide: {
      overview: '오브제 기반 기초디자인을 평가한다. 경쟁률이 높아 실기 완성도가 매우 중요하다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '패션·인테리어 소재 오브제 구성' },
        { year: '2024', topic: '일상 소품 활용 기초디자인' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 참신함' },
        { item: '구성', detail: '화면 레이아웃의 완성도' },
        { item: '채색 완성도', detail: '색채 조화와 전체 마감' },
      ],
      strategy: ['경쟁률이 높으므로 기초디자인 완성도를 최상위 수준으로 끌어올린다.', '패션·디자인 전공 특성에 맞는 세련된 색채 감각을 기른다.'],
      cautions: ['14:1 이상의 높은 경쟁률을 고려해 평균 이상의 실기 수준을 목표로 해야 한다.'],
    },
  },
  {
    name: '동덕여자대학교',
    department: '회화과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['수채화'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 수채화 실기.',
    practiceGuide: {
      overview: '수채화를 통한 회화 기초 표현 능력을 평가한다.',
      examInfo: { time: '4시간', paper: '수채화 용지', materials: '수채화 물감, 붓 지참' },
      trends: [
        { year: '2025', topic: '정물 또는 인물 수채화 표현' },
        { year: '2024', topic: '투명 수채 기법 중심 묘사' },
      ],
      scoring: [
        { item: '색채력', detail: '수채화 고유 색감 및 투명도 표현' },
        { item: '묘사력', detail: '대상 형태와 질감 표현' },
        { item: '완성도', detail: '화면 전체 마무리 수준' },
      ],
      strategy: ['수채화 투명 기법과 혼색 표현을 반복 훈련한다.', '정물·인물 등 다양한 소재로 수채화 완성도를 높인다.'],
      cautions: ['수채화는 수정이 어려워 계획적인 채색 순서와 명도 계획이 중요하다.'],
    },
  },

  // 상명대학교
  {
    name: '상명대학교',
    department: '조형예술/생활예술학부',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 50명',
    suneungRatio: '20% (수시)',
    practiceRatio: '80% (수시)',
    competitionRate: '확인필요',
    note: '수시100%. 수능20%+실기80%. 실기 비중이 매우 높음.',
    practiceGuide: {
      overview: '수능 20%+실기 80%로 실기 비중이 압도적으로 높다. 기초디자인 완성도가 합격을 결정한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 반복 패턴 구성' },
        { year: '2024', topic: '자연물과 기하 형태 조합' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석과 주제 연결력' },
        { item: '구성', detail: '화면 구성의 시각적 완성도' },
        { item: '채색', detail: '색채 완성도와 마감 수준' },
      ],
      strategy: ['실기 비중 80%를 고려해 기초디자인 훈련에 절대적인 시간을 투자한다.', '수능 최저 요건 충족 후 실기에 집중하는 전략이 효과적이다.'],
      cautions: ['수능 비중이 낮아 실기에서 승부가 나므로 기초디자인 수준을 최상으로 유지해야 한다.'],
    },
  },

  // 서울과학기술대학교
  {
    name: '서울과학기술대학교',
    department: '시각/산업/실내건축디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 50명 / 정시 약 25명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 기초디자인.',
    practiceGuide: {
      overview: '오브제와 주제어를 활용한 기초디자인 화면 구성 능력을 평가한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '공산품 오브제 구성 표현' },
        { year: '2024', topic: '자연물 + 인공물 혼합 기초디자인' },
      ],
      scoring: [
        { item: '발상', detail: '주제 해석의 창의성' },
        { item: '구성', detail: '화면 구성과 시각적 흐름' },
        { item: '완성도', detail: '채색과 마감 수준' },
      ],
      strategy: ['서울과기대 기출 오브제 경향을 분석하고 반복 훈련한다.', '이공계 감성에 맞는 논리적 화면 구성을 연습한다.'],
      cautions: ['이공계 특성상 지나치게 감성적인 구성보다 명확한 주제 전달이 중요하다.'],
    },
  },

  // 서울시립대학교
  {
    name: '서울시립대학교',
    department: '산업디자인학과',
    region: '서울',
    admissionTypes: ['정시'],
    applicationPeriod: '정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '정시 약 20명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '정시 나군. 정시100%. 수능40%+실기60%. 기초디자인.',
    practiceGuide: {
      overview: '정시만으로 선발하는 학과로, 기초디자인 실기 비중이 60%다. 수능과 실기 균형이 중요하다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '산업제품 오브제 기초디자인' },
        { year: '2024', topic: '기능성 사물 구성 표현' },
      ],
      scoring: [
        { item: '발상', detail: '산업 디자인적 감각을 반영한 구성' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '완성도', detail: '채색과 전체 마감 수준' },
      ],
      strategy: ['정시 전형이므로 수능 준비와 실기 준비를 병행하는 시간 관리가 필요하다.', '산업디자인 특성에 맞는 기능적·논리적 구성 연습을 한다.'],
      cautions: ['정시 전형 한 가지만 있어 수능 등급도 일정 수준 이상 확보해야 한다.'],
    },
  },

  // 덕성여자대학교
  {
    name: '덕성여자대학교',
    department: '디자인학부',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 20% (정시)',
    practiceRatio: '실기 100% (수시) / 80% (정시)',
    competitionRate: '확인필요',
    note: '수능20%+실기80%. 기초디자인. 실기 비중 압도적.',
    practiceGuide: {
      overview: '수능 20%+실기 80%로 실기 비중이 매우 높다. 기초디자인 완성도가 합격을 좌우한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 주제어 구성' },
        { year: '2024', topic: '복합 오브제 반복 패턴' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석과 주제 표현력' },
        { item: '구성', detail: '화면 구성의 시각적 완성도' },
        { item: '채색', detail: '색채 조화와 마감 수준' },
      ],
      strategy: ['실기 80% 비중에 맞게 기초디자인 훈련을 집중적으로 쌓는다.', '수능 부담이 낮아 실기에 더 많은 시간을 투자할 수 있다.'],
      cautions: ['실기 비중이 높은 만큼 기초디자인의 평균 수준도 높으므로 완성도를 철저히 준비해야 한다.'],
    },
  },
  {
    name: '덕성여자대학교',
    department: '회화과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['수채화', '소묘'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 20% (정시)',
    practiceRatio: '실기 100% (수시) / 80% (정시)',
    competitionRate: '확인필요',
    note: '수능20%+실기80%. 수채화 또는 소묘 선택.',
    practiceGuide: {
      overview: '수채화 또는 소묘를 선택하여 응시하는 회화 실기 시험이다. 실기 비중이 80%다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 과목에 맞는 재료 지참' },
      trends: [
        { year: '2025', topic: '정물 또는 인물 관찰 표현' },
        { year: '2024', topic: '빛과 명암 중심 표현' },
      ],
      scoring: [
        { item: '묘사력', detail: '대상 형태와 질감 표현' },
        { item: '톤/색감', detail: '명암 단계 또는 색채 조화' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
      ],
      strategy: ['소묘 또는 수채화 중 강점 과목을 선택해 집중 훈련한다.', '실기 비중 80%를 고려해 완성도를 최우선으로 준비한다.'],
      cautions: ['실기 선택 과목을 조기에 확정하고 해당 과목만 집중적으로 반복해야 한다.'],
    },
  },

  // 한성대학교
  {
    name: '한성대학교',
    department: '디자인아트학부',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 100% (정시)',
    practiceRatio: '0%',
    competitionRate: '확인필요',
    note: '비실기 전형. 수능100%로 선발.',
    practiceGuide: {
      overview: '실기 없이 수능 100%로 선발하는 비실기 전형이다. 수능 성적이 합격의 유일한 기준이다.',
      examInfo: { time: '해당 없음', paper: '해당 없음', materials: '해당 없음' },
      trends: [
        { year: '2025', topic: '비실기 전형 유지' },
        { year: '2024', topic: '비실기 전형 유지' },
      ],
      scoring: [
        { item: '수능 성적', detail: '전 과목 수능 점수 반영' },
        { item: '학생부', detail: '수시의 경우 학생부 반영 가능' },
        { item: '면접', detail: '전형에 따라 면접 포함 여부 확인' },
      ],
      strategy: ['수능 준비에 집중하고 실기 준비 시간을 수능 학습에 활용한다.', '비실기 전형 경쟁자는 수능 상위권이므로 목표 등급을 높게 설정해야 한다.'],
      cautions: ['비실기 전형이라도 디자인 관련 대학 특성상 포트폴리오를 요구하는 수시 전형이 일부 있으므로 공고를 확인해야 한다.'],
    },
  },

  // 서경대학교
  {
    name: '서경대학교',
    department: '시각미디어/패션디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '수시 약 25명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 100% (정시)',
    practiceRatio: '0%',
    competitionRate: '확인필요',
    note: '비실기 전형. 수능100%로 선발.',
    practiceGuide: {
      overview: '실기 없이 수능 100%로 선발하는 비실기 전형이다.',
      examInfo: { time: '해당 없음', paper: '해당 없음', materials: '해당 없음' },
      trends: [
        { year: '2025', topic: '비실기 전형 유지' },
        { year: '2024', topic: '비실기 전형 유지' },
      ],
      scoring: [
        { item: '수능 성적', detail: '수능 점수 전체 반영' },
        { item: '학생부', detail: '수시의 경우 학생부 반영 가능' },
        { item: '면접', detail: '전형에 따라 면접 포함 여부 확인' },
      ],
      strategy: ['수능 중심으로 준비하고 해당 전공 관련 배경 지식을 보완한다.', '수시 학생부 전형도 함께 검토해 지원 전략을 다양화한다.'],
      cautions: ['비실기 전형이지만 수능 최저 기준이 있는 경우가 있으므로 공고를 반드시 확인해야 한다.'],
    },
  },

  // 동국대학교
  {
    name: '동국대학교',
    department: '영화영상학과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['시나리오 실기'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수시/정시 모두 시나리오 실기 또는 수능+면접 전형.',
    practiceGuide: {
      overview: '시나리오 작성 실기를 통해 스토리텔링 능력과 영화적 사고를 평가한다. 면접 전형은 영화 관련 지식과 자질을 평가한다.',
      examInfo: { time: '3~4시간', paper: '지정 원고지', materials: '필기도구' },
      trends: [
        { year: '2025', topic: '사회적 이슈 반영 단편 시나리오' },
        { year: '2024', topic: '인물 갈등 구조 중심 서사' },
      ],
      scoring: [
        { item: '서사 구조', detail: '기승전결이 명확한 시나리오 구성' },
        { item: '창의성', detail: '독창적 소재와 주제 의식' },
        { item: '영화적 표현', detail: '장면 묘사와 대사의 시네마틱 완성도' },
      ],
      strategy: ['다양한 단편 시나리오를 직접 작성하며 서사 구성력을 기른다.', '영화사와 영화 이론을 학습해 면접 전형도 대비한다.'],
      cautions: ['시나리오는 소설과 달리 장면 중심으로 써야 하므로 시나리오 고유 형식을 반드시 익혀야 한다.'],
    },
  },

  // 서울여자대학교
  {
    name: '서울여자대학교',
    department: '시각/산업디자인학과',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 60% (정시)',
    practiceRatio: '실기 100% (수시) / 40% (정시)',
    competitionRate: '15.5:1',
    note: '정시 나군. 수능60%+실기40%. 기초디자인. 경쟁률 15.5:1.',
    practiceGuide: {
      overview: '수능 비중이 60%로 높고 경쟁률도 15:1 이상으로 높다. 수능과 실기 모두 균형 있게 준비해야 한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 소재 오브제 기초디자인' },
        { year: '2024', topic: '복합 구성 기초디자인' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 참신함' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '채색', detail: '색채 조화와 마감' },
      ],
      strategy: ['수능 60% 비중을 고려해 수능 등급을 안정적으로 확보한다.', '높은 경쟁률을 감안해 기초디자인도 상위권 수준으로 준비한다.'],
      cautions: ['경쟁률이 높아 수능과 실기 모두 평균 이상을 유지해야 안전하게 합격할 수 있다.'],
    },
  },

  // 추계예술대학교
  {
    name: '추계예술대학교',
    department: '서양화/동양화/조소/산업디자인',
    region: '서울',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['전공별 실기'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '0~20% (전형별)',
    practiceRatio: '80~100% (전형별)',
    competitionRate: '확인필요',
    note: '실기 위주. 수능0~20%+실기80~100%. 전공별 실기 상이.',
    practiceGuide: {
      overview: '실기 위주 전형으로 수능 비중이 거의 없다. 전공별 실기 완성도가 합격을 결정한다.',
      examInfo: { time: '전공별 상이', paper: '전공별 지정', materials: '전공별 상이' },
      trends: [
        { year: '2025', topic: '전공 특성 반영 표현 과제' },
        { year: '2024', topic: '관찰 및 창작 혼합 과제' },
      ],
      scoring: [
        { item: '전공 표현력', detail: '전공별 매체와 기법 완성도' },
        { item: '창의성', detail: '독창적 조형 언어 구사' },
        { item: '완성도', detail: '전체 작품 완성도' },
      ],
      strategy: ['수능 부담 없이 실기에 집중할 수 있는 전형 구조를 최대한 활용한다.', '지원 전공 특성에 맞는 실기를 집중적으로 훈련한다.'],
      cautions: ['실기 비중이 압도적으로 높아 실기 수준이 합격을 거의 전적으로 결정한다.'],
    },
  },

  // 한국예술종합학교 영상원 - 영화과
  {
    name: '한국예술종합학교',
    department: '영상원 영화과',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '특별전형 2026.06월 예정 / 일반전형 2026.09.28 ~ 10.01 예정',
    hasPractice: true,
    practiceSubjects: ['논술', '이야기 구성', '구술'],
    recruitCount: '45명 (특별전형 15명 + 일반전형 30명)',
    suneungRatio: '없음 (수능 반영 없음)',
    practiceRatio: '논술 50% + 구술 50% (1·2차 합산)',
    competitionRate: '확인필요',
    note: '수능 반영 없음. [일반전형] 1차: 글쓰기80%+내신20% → 2차: 이야기구성60%+구술40%. [특별전형] 외국어우수자(TOEFL 102+등) 또는 영상예술특기자(주요영화제 수상작).',
    practiceGuide: {
      overview: '한국예술종합학교 영화과는 수능 없이 논술·이야기구성·구술로만 선발합니다. 글쓰기·스토리텔링 능력과 영화적 사고가 핵심입니다. 국내 최고 수준의 영화 교육기관으로 경쟁이 매우 치열합니다.',
      examInfo: {
        time: '1차 글쓰기 150분 / 2차 이야기구성 180분 + 구술',
        paper: '본교 제공',
        materials: '필기도구 (실기재료 불필요)',
      },
      trends: [
        { year: '2025', topic: '주어진 소재·주제에 대해 이야기 구성 또는 논술 (180분), 영어 지문 포함 가능' },
        { year: '2024', topic: '이미지 자료 기반 글쓰기 또는 논술, 영화적 상상력 표현' },
      ],
      scoring: [
        { item: '글쓰기·논술 (1차, 80점)', detail: '영화적 사고, 언어적 표현력, 논리적 서술 능력' },
        { item: '이야기 구성 (2차, 60점)', detail: '주어진 조건에 맞는 서사 구성력과 연출적 상상력' },
        { item: '구술 (2차, 40점)', detail: '프로필·시험결과물 기반 질의응답, 영화에 대한 이해와 열정' },
        { item: '고교 내신 (1차, 20점)', detail: '내신 성적 반영 (비중 낮음)' },
      ],
      strategy: [
        '영화를 많이 보고 감독의 연출 의도와 서사 구조를 분석하는 습관을 기릅니다.',
        '매일 글쓰기 훈련 — 단편 시나리오, 영화 리뷰, 이야기 구성 연습이 핵심입니다.',
        '프로필(지정서식)은 영화에 대한 진지한 열정과 구체적인 경험으로 채우세요.',
        '특별전형 지원 시 공인영어성적(TOEFL 102+ 등) 또는 주요 영화제 수상작을 미리 준비하세요.',
      ],
      cautions: [
        '실기 미술 준비가 필요 없는 대신 글쓰기와 영화적 사고 능력이 당락을 결정합니다.',
        '입시 일정이 9월(일반전형) / 6월(특별전형)으로 일반 대학과 다르니 별도로 확인하세요.',
        '한예종만 목표로 삼으면 위험합니다. 반드시 다른 학교도 병행 준비하세요.',
      ],
    },
  },

  // 한국예술종합학교 영상원 - 멀티미디어영상과
  {
    name: '한국예술종합학교',
    department: '영상원 멀티미디어영상과',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '일반전형 2026.09.28 ~ 10.01 예정',
    hasPractice: true,
    practiceSubjects: ['연필소묘', '주제표현 실기', '구술'],
    recruitCount: '15명 (일반전형)',
    suneungRatio: '없음 (수능 반영 없음)',
    practiceRatio: '실기1차 80% + 내신 20% → 실기2차 50% + 구술 50%',
    competitionRate: '확인필요',
    note: '수능 반영 없음. 1차: 연필소묘(80점, 180분)+내신(20점) → 2차: 주제표현실기(50점, 300분)+구술(50점). 채색재료 자유 (목탄·콘테·스프레이·화기 금지).',
    practiceGuide: {
      overview: '한예종 멀티미디어영상과는 영상·미디어아트·인터랙티브 분야를 다루며, 연필소묘와 주제 기반 표현 실기로 선발합니다. 관찰력과 창의적 표현력이 핵심입니다.',
      examInfo: {
        time: '1차 소묘 180분 / 2차 주제표현 300분',
        paper: '켄트지 (본교 제공)',
        materials: '1차: 연필 / 2차: 채색재료 자유 (목탄·콘테·스프레이·화기 금지)',
      },
      trends: [
        { year: '2025', topic: '1차: 사물 관찰 소묘 / 2차: 제시된 주제를 재료로 창의적 표현 (300분)' },
        { year: '2024', topic: '1차: 정물 소묘 / 2차: 미디어·영상 개념 기반 주제 표현' },
      ],
      scoring: [
        { item: '연필소묘 (1차, 80점)', detail: '사물 관찰력과 묘사 표현력' },
        { item: '주제표현 실기 (2차, 50점)', detail: '창의력, 표현성, 재료 활용 능력' },
        { item: '구술 (2차, 50점)', detail: '1·2차 실기 결과물·프로필 질의응답, 학업능력 평가' },
        { item: '고교 내신 (1차, 20점)', detail: '내신 성적 반영' },
      ],
      strategy: [
        '소묘 기본기를 탄탄히 다져야 합니다. 사물의 형태·명암·질감 묘사 능력이 핵심입니다.',
        '2차 주제표현은 재료 제한이 적으므로 다양한 채색 재료를 경험해두세요.',
        '멀티미디어·미디어아트 전시, 작가 작품을 많이 보고 개념적 사고를 키우세요.',
        '구술에서 실기 결과물의 창작 의도를 논리적으로 설명하는 연습을 해두세요.',
      ],
      cautions: [
        '목탄·콘테·스프레이·화기는 2차 실기에서 사용 금지입니다.',
        '한예종 특유의 개념적·실험적 접근을 요구하므로 단순 기술 훈련보다 예술적 사고 발전이 중요합니다.',
        '일반 미대와 입시 일정이 다릅니다. 원서접수가 9월 말~10월 초임을 주의하세요.',
      ],
    },
  },

  // 한국예술종합학교 영상원 - 애니메이션과
  {
    name: '한국예술종합학교',
    department: '영상원 애니메이션과',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '특별전형(3D특기자) 2026.06월 예정 / 일반전형 2026.09.28 ~ 10.01 예정',
    hasPractice: true,
    practiceSubjects: ['스토리보드·만화·일러스트 실기', '포트폴리오', '구술'],
    recruitCount: '15명 (3D특기자 특별전형 3명 + 일반전형 12명)',
    suneungRatio: '없음 (수능 반영 없음)',
    practiceRatio: '실기1차 70%+내신30% → 실기2차 50%+구술50%',
    competitionRate: '확인필요',
    note: '수능 반영 없음. [일반] 1차: 만화·일러스트형식 스토리구성(70점, 180분)+내신(30점) → 2차: 스토리구성(50점, 360분)+구술+포트폴리오. [특별전형] 3D특기자: 포트폴리오예비심사→실기+구술(3D시연포함).',
    practiceGuide: {
      overview: '한예종 애니메이션과는 만화·일러스트 형식의 스토리 구성 실기와 포트폴리오로 선발합니다. 드로잉 기본기보다 내러티브·연출력·스토리텔링 능력을 더 중요하게 평가합니다.',
      examInfo: {
        time: '1차 스토리구성 180분 / 2차 스토리구성 360분 + 구술',
        paper: '1차: 8절 스케치북(본교제공) / 2차: 4절 켄트지·화판(본교제공)',
        materials: '재료·색상 자유 (개인 준비)',
      },
      trends: [
        { year: '2025', topic: '만화·일러스트 형식 스토리 구성과 그림 — 내러티브·드로잉·연출력 평가' },
        { year: '2024', topic: '주어진 주제로 장면 연출 및 캐릭터 감정 표현 스토리보드 구성' },
      ],
      scoring: [
        { item: '스토리 구성·연출 (1차, 70점)', detail: '이야기 구성력, 장면 연출, 만화·일러스트 표현' },
        { item: '내러티브·드로잉·연출 (2차, 50점)', detail: '완성도 높은 스토리보드, 드로잉 능력, 연출력' },
        { item: '구술 (2차, 50점)', detail: '포트폴리오·실기결과물 기반 질의응답, 창작 의도 설명' },
        { item: '고교 내신 (1차, 30점)', detail: '내신 성적 반영' },
      ],
      strategy: [
        '매주 단편 만화·스토리보드를 완성하는 훈련이 필수입니다. 6컷~12컷 단편을 꾸준히 그려보세요.',
        '포트폴리오는 최근 2년 내 작품 20점 이내로 A3 스크랩북에 구성하세요.',
        '3D 특기자 전형 지원 시 3D 애니메이션 동영상이 포함된 포트폴리오와 USB 3개를 준비하세요.',
        '애니메이션 명작(지브리, 픽사, 국내 단편 등)을 분석하며 연출 감각을 키우세요.',
      ],
      cautions: [
        '포트폴리오는 타인 작품·대리 제작·공동작업자 미명시 시 합격이 취소됩니다.',
        '재료는 자유이지만 화판은 본교에서 제공하므로 별도 준비 불필요합니다.',
        '특별전형(6월)과 일반전형(9월) 일정이 다르니 지원 유형을 먼저 결정하세요.',
      ],
    },
  },

  // 한국예술종합학교 영상원 - 방송영상과
  {
    name: '한국예술종합학교',
    department: '영상원 방송영상과',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '일반전형 2026.09.28 ~ 10.01 예정',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '20명 (일반전형)',
    suneungRatio: '없음 (수능 반영 없음)',
    practiceRatio: '없음 (논술+글쓰기+구술 전형)',
    competitionRate: '확인필요',
    note: '수능 반영 없음. 1차: 언어능력평가 논술(50점)+내신(50점) → 2차: 영상물글쓰기·논술(50점)+구술(50점). 실기 미술 불필요.',
    practiceGuide: {
      overview: '한예종 방송영상과는 실기 미술 없이 논술·글쓰기·구술로 선발합니다. 방송·미디어에 대한 깊은 이해와 언어적 표현력이 핵심이며, 내신 반영 비중이 상대적으로 높습니다.',
      examInfo: {
        time: '1차 논술 (시간 별도 공고) / 2차 영상물 글쓰기·논술 180분 + 구술',
        paper: '본교 제공',
        materials: '필기도구만 필요',
      },
      trends: [
        { year: '2025', topic: '2차: 영상물에 대한 글쓰기 또는 주어진 주제 논술 (180분)' },
        { year: '2024', topic: '언론·방송·미디어 관련 시사 이슈 논술 및 영상물 비평' },
      ],
      scoring: [
        { item: '언어능력평가·논술 (1차, 50점)', detail: '논리적 글쓰기, 언어 표현력' },
        { item: '고교 내신 (1차, 50점)', detail: '내신 성적 반영 (비중 높음)' },
        { item: '영상물 글쓰기·논술 (2차, 50점)', detail: '영상 분석 능력, 비판적 사고' },
        { item: '구술 (2차, 50점)', detail: '프로필·시험결과물 기반 질의응답' },
      ],
      strategy: [
        '뉴스·다큐멘터리·방송 프로그램을 비판적으로 분석하고 글로 정리하는 훈련을 하세요.',
        '내신 반영 비중이 50점으로 높으니 학교 성적 관리가 중요합니다.',
        '프로필에 방송·미디어 관련 활동 경험(학교 방송부, 영상 제작 등)을 구체적으로 담으세요.',
        '논술은 주장-근거-예시 구조를 명확히 하는 연습을 꾸준히 하세요.',
      ],
      cautions: [
        '실기 미술이 필요 없지만 내신 성적(50점) 비중이 높아 성적 관리가 필수입니다.',
        '답안지에 본인·가족 성명, 출신학교 등 인적사항 기재가 금지되어 있으니 주의하세요.',
        '일반 미대와 입시 일정이 다릅니다.',
      ],
    },
  },

  // 한국예술종합학교 영상원 - 영상이론과
  {
    name: '한국예술종합학교',
    department: '영상원 영상이론과',
    region: '서울',
    admissionTypes: ['수시'],
    applicationPeriod: '일반전형 2026.09.28 ~ 10.01 예정',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '10명 (일반전형)',
    suneungRatio: '없음 (수능 반영 없음)',
    practiceRatio: '없음 (논술+구술 전형)',
    competitionRate: '확인필요',
    note: '수능 반영 없음. 1차: 언어능력평가(60점)+내신(40점) → 2차: 영상이론 논술+구술. 극소수 선발, 경쟁 매우 치열.',
    practiceGuide: {
      overview: '한예종 영상이론과는 영화·영상 이론·비평 연구를 위한 학과로, 논술과 구술로 선발합니다. 영화사·영상미학·비평 능력이 핵심이며 국내 유일의 영상이론 전문 학과입니다.',
      examInfo: {
        time: '1차 논술 (시간 별도 공고) / 2차 논술+구술',
        paper: '본교 제공',
        materials: '필기도구만 필요',
      },
      trends: [
        { year: '2025', topic: '영화·영상 관련 이론 주제 논술 및 구술 면접' },
        { year: '2024', topic: '영화사 및 영상미학 관련 비평적 논술' },
      ],
      scoring: [
        { item: '언어능력평가·논술 (1차, 60점)', detail: '영상·영화 관련 이론적 이해와 논리적 서술 능력' },
        { item: '고교 내신 (1차, 40점)', detail: '내신 성적 반영' },
        { item: '논술·구술 (2차)', detail: '영상이론·비평 능력, 학문적 잠재력' },
      ],
      strategy: [
        '영화사(세계영화사, 한국영화사)와 영상미학 기초 서적을 읽고 핵심 개념을 정리하세요.',
        '영화 비평문을 꾸준히 작성하며 논리적 글쓰기 능력을 키우세요.',
        '다양한 장르·시대·국가의 영화를 폭넓게 감상하고 비판적으로 분석하세요.',
        '내신(40점) 비중이 높으니 학교 성적 관리를 병행하세요.',
      ],
      cautions: [
        '10명 선발로 경쟁이 매우 치열합니다. 한예종만 목표로 삼으면 위험합니다.',
        '실기 미술이 아닌 영상 이론·비평 능력이 핵심이므로 이론 공부에 집중하세요.',
      ],
    },
  },

  // ======================== 경기/인천 ========================

  // 가천대학교
  {
    name: '가천대학교',
    department: '디자인학부/실내건축학과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 60명',
    suneungRatio: '20% (수시)',
    practiceRatio: '80% (수시)',
    competitionRate: '확인필요',
    note: '수시100%. 수능20%+실기80%. 기초디자인.',
    practiceGuide: {
      overview: '수시 전형만 운영하며 수능 20%+실기 80%로 실기 비중이 높다. 기초디자인 완성도가 당락을 좌우한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 기초디자인 구성' },
        { year: '2024', topic: '자연물 + 인공물 혼합 표현' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 창의성' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '채색', detail: '색채 조화와 마감 수준' },
      ],
      strategy: ['실기 비중 80%를 고려해 기초디자인 완성도 훈련에 집중한다.', '수능 최저 기준 충족 후 실기에 전략적으로 투자한다.'],
      cautions: ['수시 전형만 있으므로 9월 원서 접수 전까지 실기 준비를 마쳐야 한다.'],
    },
  },

  // 인하대학교
  {
    name: '인하대학교',
    department: '조형예술학과',
    region: '인천',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['인물수채화'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 인물수채화 실기.',
    practiceGuide: {
      overview: '인물을 주제로 한 수채화 실기를 평가한다. 인물 묘사력과 수채화 표현 기술이 핵심이다.',
      examInfo: { time: '4시간', paper: '수채화 용지', materials: '수채화 물감, 붓 지참' },
      trends: [
        { year: '2025', topic: '인물 전신 또는 상반신 수채화' },
        { year: '2024', topic: '인물 + 배경 구성 수채화' },
      ],
      scoring: [
        { item: '인물 묘사', detail: '인체 비례와 표정·포즈 표현력' },
        { item: '수채화 기법', detail: '투명도와 색채 조화' },
        { item: '완성도', detail: '전체 화면 마감 수준' },
      ],
      strategy: ['인물 수채화를 집중적으로 반복 훈련하며 인체 비례와 채색 기술을 동시에 향상시킨다.', '다양한 포즈와 조명 조건의 인물을 연습한다.'],
      cautions: ['인물 수채화는 기초디자인과 전혀 다른 실기 유형이므로 특화된 전문 훈련이 필요하다.'],
    },
  },

  // 경기대학교
  {
    name: '경기대학교',
    department: '디자인학부/파인아트학부',
    region: '경기',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '소묘'],
    recruitCount: '수시 약 50명 / 정시 약 25명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 디자인학부는 기초디자인, 파인아트학부는 소묘.',
    practiceGuide: {
      overview: '디자인학부는 기초디자인, 파인아트학부는 소묘로 나뉜다. 지원 학부에 맞는 실기를 준비해야 한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '학부별 상이 (채색 또는 소묘 재료)' },
      trends: [
        { year: '2025', topic: '기초디자인: 복합 오브제 구성 / 소묘: 정물 정밀 묘사' },
        { year: '2024', topic: '기초디자인: 주제어 구성 / 소묘: 인물+정물 혼합' },
      ],
      scoring: [
        { item: '실기 유형 이해', detail: '기초디자인 또는 소묘 유형에 맞는 표현' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
        { item: '표현력', detail: '형태·색채·명암 처리 능력' },
      ],
      strategy: ['지원 학부를 조기에 결정하고 해당 실기 유형에 특화된 훈련을 한다.', '기초디자인과 소묘는 전혀 다른 훈련이므로 분리해서 준비한다.'],
      cautions: ['디자인학부와 파인아트학부의 실기 과목이 다르므로 혼동하지 않도록 공고를 꼼꼼히 확인해야 한다.'],
    },
  },

  // 인천대학교
  {
    name: '인천대학교',
    department: '서양화전공',
    region: '인천',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['수채화'],
    recruitCount: '수시 약 20명',
    suneungRatio: '0%',
    practiceRatio: '100%',
    competitionRate: '확인필요',
    note: '수시100%. 실기100%. 수채화.',
    practiceGuide: {
      overview: '수능 반영 없이 실기 100%로 선발한다. 수채화 완성도가 합격의 전부를 결정한다.',
      examInfo: { time: '4시간', paper: '수채화 용지', materials: '수채화 물감, 붓 지참' },
      trends: [
        { year: '2025', topic: '정물 또는 인물 수채화' },
        { year: '2024', topic: '투명 수채 기법 표현' },
      ],
      scoring: [
        { item: '색채력', detail: '수채화 고유의 투명한 색감 표현' },
        { item: '묘사력', detail: '대상 형태와 질감 표현' },
        { item: '완성도', detail: '전체 화면 마감 수준' },
      ],
      strategy: ['수능 부담 없이 수채화 훈련에 집중할 수 있는 환경을 만든다.', '다양한 소재의 수채화를 반복 연습해 완성도를 높인다.'],
      cautions: ['실기 100% 전형이므로 수채화 수준이 절대적인 당락 기준이다.'],
    },
  },

  // 명지대학교
  {
    name: '명지대학교',
    department: '미술학부/디자인학부',
    region: '경기',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '기초디자인'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 미술학부는 소묘, 디자인학부는 기초디자인.',
    practiceGuide: {
      overview: '미술학부는 소묘, 디자인학부는 기초디자인으로 실기 과목이 구분된다. 지원 학부에 맞게 준비해야 한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '학부별 상이' },
      trends: [
        { year: '2025', topic: '소묘: 정물 정밀 묘사 / 기초디자인: 오브제 구성' },
        { year: '2024', topic: '소묘: 인물·정물 혼합 / 기초디자인: 주제어 구성' },
      ],
      scoring: [
        { item: '실기 유형 이해', detail: '소묘 또는 기초디자인 유형에 맞는 표현' },
        { item: '묘사·구성력', detail: '형태 정확도 또는 화면 구성 완성도' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
      ],
      strategy: ['지원 학부를 확정하고 해당 실기 유형에 집중 훈련한다.', '기출 경향을 분석해 자주 등장하는 소재를 반복 연습한다.'],
      cautions: ['미술학부와 디자인학부 실기가 달라 중복 준비 시 효율이 낮아질 수 있다.'],
    },
  },

  // 수원대학교
  {
    name: '수원대학교',
    department: '시각디자인/회화과',
    region: '경기',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '소묘'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 시각디자인은 기초디자인, 회화과는 소묘.',
    practiceGuide: {
      overview: '시각디자인은 기초디자인, 회화과는 소묘를 실기 과목으로 사용한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '전공별 상이' },
      trends: [
        { year: '2025', topic: '기초디자인: 일상 오브제 구성 / 소묘: 정물 관찰 묘사' },
        { year: '2024', topic: '기초디자인: 복합 오브제 / 소묘: 명암 중심 정물' },
      ],
      scoring: [
        { item: '실기 유형 이해', detail: '기초디자인 또는 소묘 방식에 맞는 표현' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
        { item: '표현력', detail: '채색 또는 명암 표현 능력' },
      ],
      strategy: ['지원 전공을 결정하고 해당 실기 유형만 집중 훈련한다.', '수원대 기출 경향을 분석해 반복 연습한다.'],
      cautions: ['기초디자인과 소묘는 준비 방식이 완전히 달라 전공 결정을 빨리 내려야 한다.'],
    },
  },

  // ======================== 충청 ========================

  // 충남대학교
  {
    name: '충남대학교',
    department: '디자인창의학과',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 25명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 기초디자인. 충청권 국립대.',
    practiceGuide: {
      overview: '충청권 국립대로 안정적인 선호도를 보인다. 기초디자인 완성도와 수능 점수를 균형 있게 준비해야 한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 반복 구성' },
        { year: '2024', topic: '자연물 주제 기초디자인' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석과 주제 표현력' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '채색', detail: '색채 조화와 마감 수준' },
      ],
      strategy: ['국립대 특성상 수능 점수도 중요하므로 실기와 수능을 균형 있게 준비한다.', '기출 오브제 경향을 분석해 반복 훈련한다.'],
      cautions: ['충청권 수험생 경쟁이 집중되므로 완성도 높은 실기가 필수다.'],
    },
  },

  // 한남대학교
  {
    name: '한남대학교',
    department: '회화과',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '수채화'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 소묘 또는 수채화 선택.',
    practiceGuide: {
      overview: '소묘 또는 수채화를 선택해 응시하는 회화 실기다. 실기 비중이 70%로 높다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 과목에 맞는 재료 지참' },
      trends: [
        { year: '2025', topic: '정물 관찰 묘사 (소묘/수채 공통)' },
        { year: '2024', topic: '인물 또는 정물 혼합 구성' },
      ],
      scoring: [
        { item: '묘사력', detail: '형태 정확도와 질감 표현' },
        { item: '명암/색감', detail: '톤 단계 또는 색채 조화' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
      ],
      strategy: ['소묘와 수채화 중 더 강한 과목을 조기에 결정해 집중 훈련한다.', '정물 구성 표현력을 꾸준히 쌓는다.'],
      cautions: ['선택 과목을 늦게 결정하면 두 과목 모두 준비 부족으로 이어질 수 있다.'],
    },
  },

  // 목원대학교
  {
    name: '목원대학교',
    department: '시각디자인과',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 기초디자인.',
    practiceGuide: {
      overview: '대전 소재 사립대로 디자인 실기 비중이 높다. 기초디자인 완성도가 합격의 핵심이다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '복합 오브제 기초디자인 구성' },
        { year: '2024', topic: '단일 오브제 반복 패턴' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 독창성' },
        { item: '구성', detail: '화면 균형과 리듬감' },
        { item: '채색', detail: '색채 완성도' },
      ],
      strategy: ['기초디자인 70% 비중에 맞게 실기 훈련에 집중한다.', '목원대 기출 오브제 경향을 파악해 반복 연습한다.'],
      cautions: ['수능 최저 기준 확인 후 전략적으로 지원해야 한다.'],
    },
  },

  // 청주대학교
  {
    name: '청주대학교',
    department: '산업디자인학과',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '발상과표현'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 기초디자인 또는 발상과표현 선택.',
    practiceGuide: {
      overview: '충북 소재 사립대로 산업디자인 전공 실기를 평가한다. 기초디자인과 발상과표현 중 선택 응시한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '제품 오브제 기초디자인 구성' },
        { year: '2024', topic: '발상과표현: 생활 소재 주제' },
      ],
      scoring: [
        { item: '발상', detail: '주제 해석과 표현의 창의성' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '완성도', detail: '채색 마감 수준' },
      ],
      strategy: ['두 유형 중 본인에게 유리한 과목을 조기에 선택해 집중 훈련한다.', '산업디자인 감각을 키우기 위해 제품 스케치 연습을 병행한다.'],
      cautions: ['두 과목을 모두 준비하면 완성도가 떨어질 수 있으니 하나에 집중한다.'],
    },
  },

  // ======================== 대구/경북 ========================

  // 계명대학교
  {
    name: '계명대학교',
    department: '시각디자인과',
    region: '대구/경북',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 25명 / 정시 약 12명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 기초디자인. 대구 대표 사립대.',
    practiceGuide: {
      overview: '대구 대표 사립대로 디자인 계열 선호도가 높다. 기초디자인 완성도가 당락을 결정한다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 주제어 기초디자인' },
        { year: '2024', topic: '자연물 + 인공물 복합 구성' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 창의성과 참신함' },
        { item: '구성', detail: '화면 구성의 시각적 완성도' },
        { item: '채색', detail: '색채 조화와 마감 수준' },
      ],
      strategy: ['대구·경북권 경쟁이 높으므로 기초디자인 완성도를 철저히 끌어올린다.', '기출 오브제 분석을 통해 주제 해석 훈련을 반복한다.'],
      cautions: ['경쟁률이 높아 평균 이상의 실기 수준이 필요하다.'],
    },
  },

  // 영남대학교
  {
    name: '영남대학교',
    department: '시각디자인학과',
    region: '대구/경북',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '발상과표현'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 기초디자인 또는 발상과표현 선택.',
    practiceGuide: {
      overview: '경북 소재 주요 사립대로 시각디자인 분야 인지도가 높다. 수능과 실기 비율이 균형 잡혀 있다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '오브제 주제어 기초디자인' },
        { year: '2024', topic: '발상과표현: 사회 이슈 시각화' },
      ],
      scoring: [
        { item: '발상', detail: '주제 해석력과 창의성' },
        { item: '구성', detail: '화면 레이아웃과 시각 흐름' },
        { item: '채색', detail: '색채 완성도' },
      ],
      strategy: ['수능 40% 비중을 고려해 수능 공부도 소홀히 하지 않는다.', '두 유형 중 유리한 과목을 조기 선택해 집중한다.'],
      cautions: ['수능 최저 기준을 반드시 확인하고 지원 전략을 세워야 한다.'],
    },
  },

  // 경북대학교
  {
    name: '경북대학교',
    department: '디자인학부',
    region: '대구/경북',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 30명 / 정시 약 15명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수능50%+실기50%. 대구 국립대. 수능 비중이 높은 편.',
    practiceGuide: {
      overview: '대구 소재 국립대로 수능과 실기 비중이 동일하다. 수능 점수가 합격에 크게 영향을 미친다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '복합 오브제 기초디자인' },
        { year: '2024', topic: '단일 주제 반복 패턴 구성' },
      ],
      scoring: [
        { item: '발상', detail: '주제 해석의 독창성' },
        { item: '구성', detail: '화면 균형과 완성도' },
        { item: '채색', detail: '색채 조화와 마감' },
      ],
      strategy: ['국립대 특성상 수능 점수가 중요하므로 수능 준비를 병행한다.', '실기 50% 비중에 맞게 기초디자인 완성도도 꾸준히 유지한다.'],
      cautions: ['수능 최저 기준이 타 사립대보다 높을 수 있으므로 반드시 사전 확인이 필요하다.'],
    },
  },

  // ======================== 부산/경남 ========================

  // 부산대학교
  {
    name: '부산대학교',
    department: '조형학부',
    region: '부산/경남',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인', '소묘'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수능50%+실기50%. 부산 국립대. 디자인/회화 통합 선발.',
    practiceGuide: {
      overview: '부산 소재 국립대로 수능과 실기 비중이 동일하다. 조형학부 내 전공 분리 선발로 지원 시 전공 확인이 필요하다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '전공별 상이' },
      trends: [
        { year: '2025', topic: '기초디자인: 오브제 구성 / 소묘: 정물 관찰 묘사' },
        { year: '2024', topic: '기초디자인: 복합 오브제 / 소묘: 명암 중심' },
      ],
      scoring: [
        { item: '전공 적합성', detail: '지원 전공에 맞는 표현 방식' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
        { item: '구성/묘사력', detail: '디자인 구성 또는 소묘 묘사력' },
      ],
      strategy: ['국립대 수능 비중 50%를 고려해 수능 준비를 철저히 병행한다.', '지원 전공에 맞는 실기 유형을 조기에 확정하고 집중 훈련한다.'],
      cautions: ['수능 최저 기준이 높으므로 반드시 사전 확인 후 지원 전략을 세워야 한다.'],
    },
  },

  // 동아대학교
  {
    name: '동아대학교',
    department: '회화과',
    region: '부산/경남',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '수채화'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 소묘 또는 수채화 선택.',
    practiceGuide: {
      overview: '부산 주요 사립대로 회화 전공 실기 비중이 높다. 소묘 또는 수채화를 선택해 응시한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 과목에 맞는 재료 지참' },
      trends: [
        { year: '2025', topic: '정물 관찰 묘사 (소묘/수채 공통)' },
        { year: '2024', topic: '빛과 명암 중심 표현' },
      ],
      scoring: [
        { item: '묘사력', detail: '형태와 질감 정확도' },
        { item: '톤/색감', detail: '명암 단계 또는 색채 완성도' },
        { item: '완성도', detail: '화면 마감 수준' },
      ],
      strategy: ['소묘와 수채화 중 강점 과목을 조기에 결정해 집중 훈련한다.', '부산·경남권 회화 기출 경향을 분석해 대비한다.'],
      cautions: ['두 과목을 동시에 준비하면 모두 완성도가 낮아질 수 있다.'],
    },
  },

  // 경성대학교
  {
    name: '경성대학교',
    department: '패션디자인학과',
    region: '부산/경남',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['발상과표현'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 발상과표현. 패션 감성 중요.',
    practiceGuide: {
      overview: '패션디자인 전공으로 발상과표현 실기에서 패션 감성을 표현하는 능력을 평가한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '패션 소재 발상과표현' },
        { year: '2024', topic: '일상 소재의 패션 감각 시각화' },
      ],
      scoring: [
        { item: '발상', detail: '패션 감성을 살린 주제 해석' },
        { item: '표현력', detail: '색채와 조형의 완성도' },
        { item: '완성도', detail: '화면 마감 수준' },
      ],
      strategy: ['패션 잡지, 트렌드 자료 등을 참고해 패션 감각을 키운다.', '발상과표현 기출 주제를 분석해 다양한 해석 연습을 쌓는다.'],
      cautions: ['일반 기초디자인과 달리 패션 감성이 반영되어야 하므로 전공 이해가 중요하다.'],
    },
  },

  // ======================== 광주/전라 ========================

  // 조선대학교
  {
    name: '조선대학교',
    department: '미술학부',
    region: '광주/전라',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '수채화', '기초디자인'],
    recruitCount: '수시 약 40명 / 정시 약 20명',
    suneungRatio: '없음 (수시) / 30% (정시)',
    practiceRatio: '실기 100% (수시) / 70% (정시)',
    competitionRate: '확인필요',
    note: '수능30%+실기70%. 전공별 실기 과목 상이. 광주 대표 사립대.',
    practiceGuide: {
      overview: '광주 대표 사립대로 미술학부 내 회화/디자인 전공이 분리 운영된다. 전공에 따라 실기 과목이 다르다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '전공별 상이' },
      trends: [
        { year: '2025', topic: '회화: 정물 관찰 묘사 / 디자인: 오브제 기초디자인' },
        { year: '2024', topic: '회화: 빛과 명암 / 디자인: 복합 오브제' },
      ],
      scoring: [
        { item: '전공 적합성', detail: '지원 전공에 맞는 표현 방식' },
        { item: '완성도', detail: '화면 전체 마감 수준' },
        { item: '표현력', detail: '묘사력 또는 구성력' },
      ],
      strategy: ['전공을 조기에 확정하고 해당 실기 유형에만 집중한다.', '광주·전라권 기출 경향을 분석해 준비한다.'],
      cautions: ['미술학부 내 전공이 나뉘므로 지원 전공의 실기 유형을 정확히 파악해야 한다.'],
    },
  },

  // 전남대학교
  {
    name: '전남대학교',
    department: '디자인학과',
    region: '광주/전라',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 25명 / 정시 약 12명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수능50%+실기50%. 광주 국립대. 수능 비중 높은 편.',
    practiceGuide: {
      overview: '광주 소재 국립대로 수능과 실기 비중이 동일하다. 수능 점수가 합격에 크게 영향을 미친다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 기초디자인 구성' },
        { year: '2024', topic: '자연물 주제 반복 패턴' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석과 주제 표현력' },
        { item: '구성', detail: '화면 구성의 완성도' },
        { item: '채색', detail: '색채 조화와 마감' },
      ],
      strategy: ['국립대 특성상 수능 50% 비중을 철저히 준비한다.', '기초디자인 완성도도 꾸준히 유지한다.'],
      cautions: ['수능 최저 기준이 높으므로 반드시 사전 확인이 필요하다.'],
    },
  },

  // 전북대학교
  {
    name: '전북대학교',
    department: '산업디자인학과',
    region: '광주/전라',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수능50%+실기50%. 전북 국립대.',
    practiceGuide: {
      overview: '전주 소재 국립대로 산업디자인 전공 실기를 평가한다. 수능과 실기 비중이 동일하다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '제품 오브제 기초디자인' },
        { year: '2024', topic: '일상 소재 복합 구성' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석과 창의성' },
        { item: '구성', detail: '화면 레이아웃 완성도' },
        { item: '채색', detail: '색채 마감 수준' },
      ],
      strategy: ['수능 50%를 고려해 수능 준비를 병행한다.', '산업디자인 감각을 키우기 위해 제품 스케치 연습을 병행한다.'],
      cautions: ['국립대 수능 최저 기준을 반드시 확인해야 한다.'],
    },
  },

  // ======================== 강원/기타 ========================

  // 강원대학교
  {
    name: '강원대학교',
    department: '디자인학과',
    region: '강원/기타',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['기초디자인'],
    recruitCount: '수시 약 20명 / 정시 약 10명',
    suneungRatio: '없음 (수시) / 50% (정시)',
    practiceRatio: '실기 100% (수시) / 50% (정시)',
    competitionRate: '확인필요',
    note: '수능50%+실기50%. 강원 국립대.',
    practiceGuide: {
      overview: '춘천 소재 국립대로 수능과 실기 비중이 동일하다. 강원권 수험생에게 유리한 환경이다.',
      examInfo: { time: '4시간', paper: '켄트지 3절', materials: '채색 재료 자유 (지참)' },
      trends: [
        { year: '2025', topic: '일상 오브제 기초디자인' },
        { year: '2024', topic: '자연물 주제 구성' },
      ],
      scoring: [
        { item: '발상', detail: '오브제 해석의 창의성' },
        { item: '구성', detail: '화면 완성도' },
        { item: '채색', detail: '색채 조화' },
      ],
      strategy: ['수능 50% 비중을 고려해 수능 준비를 소홀히 하지 않는다.', '기초디자인 기출 경향을 분석해 반복 훈련한다.'],
      cautions: ['국립대 특성상 수능 최저 기준이 높을 수 있으므로 반드시 확인해야 한다.'],
    },
  },

  // 제주대학교
  {
    name: '제주대학교',
    department: '미술학과',
    region: '강원/기타',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: true,
    practiceSubjects: ['소묘', '수채화'],
    recruitCount: '수시 약 15명 / 정시 약 8명',
    suneungRatio: '없음 (수시) / 40% (정시)',
    practiceRatio: '실기 100% (수시) / 60% (정시)',
    competitionRate: '확인필요',
    note: '수능40%+실기60%. 제주 국립대. 소묘 또는 수채화 선택.',
    practiceGuide: {
      overview: '제주 소재 국립대로 미술 전공 실기를 평가한다. 소묘 또는 수채화를 선택해 응시한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '선택 과목에 맞는 재료 지참' },
      trends: [
        { year: '2025', topic: '정물 관찰 묘사 (소묘/수채 공통)' },
        { year: '2024', topic: '자연물 또는 정물 표현' },
      ],
      scoring: [
        { item: '묘사력', detail: '형태와 질감 정확도' },
        { item: '톤/색감', detail: '명암 단계 또는 색채 조화' },
        { item: '완성도', detail: '화면 마감 수준' },
      ],
      strategy: ['소묘와 수채화 중 강점 과목을 조기에 결정해 집중 훈련한다.', '제주대 기출 경향을 파악해 준비한다.'],
      cautions: ['제주 거주자 외에는 기숙사 등 생활 환경도 고려해 지원 전략을 세워야 한다.'],
    },
  },

  // ======================== 웹툰/영상/애니메이션 특화 ========================

  // 서울예술대학교 - 만화창작과
  {
    name: '서울예술대학교',
    department: '만화창작과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['만화/웹툰 실기'],
    recruitCount: '수시 약 30명',
    suneungRatio: '없음 (실기 중심)',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 포트폴리오 + 실기. 웹툰·만화 분야 최고 명문.',
    practiceGuide: {
      overview: '서울예대 만화창작과는 국내 웹툰·만화 분야 최고 명문으로 꼽힌다. 포트폴리오의 스토리텔링과 캐릭터 표현력이 당락을 결정한다.',
      examInfo: { time: '4시간 (실기) + 포트폴리오 제출', paper: '지정 용지', materials: '펜, 마커, 채색 재료 자유' },
      trends: [
        { year: '2025', topic: '주어진 주제로 단편 만화 4~8컷 구성' },
        { year: '2024', topic: '캐릭터 설정 + 감정 표현 스토리 전개' },
      ],
      scoring: [
        { item: '스토리텔링', detail: '기승전결 구성력과 연출력' },
        { item: '캐릭터', detail: '개성 있는 캐릭터 표현과 감정 묘사' },
        { item: '데생/소묘', detail: '기초 묘사력과 인체 표현' },
        { item: '포트폴리오', detail: '독창적 세계관과 작품 완성도' },
      ],
      strategy: ['단편 웹툰 완성 연습을 꾸준히 하며 스토리 구성력을 키운다.', '포트폴리오는 장르 다양성보다 자신만의 색깔이 드러나는 작품으로 구성한다.', '인체 데생과 배경 묘사 기본기를 탄탄히 쌓는다.'],
      cautions: ['단순한 그림 실력보다 이야기를 만드는 능력이 더 중요하게 평가된다.', '포트폴리오 미완성 작품은 감점 요인이 될 수 있다.'],
    },
  },

  // 서울예술대학교 - 영화과
  {
    name: '서울예술대학교',
    department: '영화과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: false,
    practiceSubjects: ['면접', '포트폴리오'],
    recruitCount: '수시 약 30명',
    suneungRatio: '없음',
    practiceRatio: '100% (면접+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 면접+포트폴리오. 연출·촬영·편집 등 세부 전공 선택.',
    practiceGuide: {
      overview: '영화 연출, 촬영, 편집 등 세부 전공으로 구분되며 포트폴리오와 심층 면접으로 선발한다. 지원 전공에 대한 명확한 지원 동기와 결과물이 중요하다.',
      examInfo: { time: '면접 20~30분', paper: '해당없음', materials: '포트폴리오 제출 (영상, 시나리오, 사진 등)' },
      trends: [
        { year: '2025', topic: '자신이 만든 단편 영상 or 시나리오 기반 면접' },
        { year: '2024', topic: '지원 동기 및 영화적 관심사 심층 면접' },
      ],
      scoring: [
        { item: '포트폴리오', detail: '자체 제작 영상, 시나리오, 사진 등 창작물 완성도' },
        { item: '면접', detail: '영화에 대한 이해도와 지원 동기의 진정성' },
        { item: '예술적 감각', detail: '영상 언어에 대한 이해와 표현 의지' },
      ],
      strategy: ['스마트폰으로라도 단편 영상을 직접 만들어 포트폴리오에 포함시킨다.', '좋아하는 영화 감독과 작품을 깊이 분석하고 면접에서 자신의 언어로 말할 수 있도록 준비한다.'],
      cautions: ['영상 제작 경험이 전혀 없으면 면접에서 불리하다.', '단순히 영화를 좋아한다는 수준의 면접 답변은 부족하다.'],
    },
  },

  // 서울예술대학교 - 애니메이션과
  {
    name: '서울예술대학교',
    department: '애니메이션과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['드로잉 실기', '포트폴리오'],
    recruitCount: '수시 약 25명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 드로잉 실기 + 포트폴리오. 애니메이션 연출·제작 역량 평가.',
    practiceGuide: {
      overview: '애니메이션 연출·캐릭터·배경 등 분야별 표현 능력을 평가한다. 드로잉 기본기와 함께 움직임에 대한 이해가 중요하다.',
      examInfo: { time: '4시간 (드로잉) + 포트폴리오 제출', paper: '지정 용지', materials: '펜, 마커, 채색 재료 자유' },
      trends: [
        { year: '2025', topic: '캐릭터 감정 표현 + 동작 연속 드로잉' },
        { year: '2024', topic: '주어진 스토리 기반 장면 연출 드로잉' },
      ],
      scoring: [
        { item: '드로잉', detail: '캐릭터와 배경의 기초 묘사력' },
        { item: '움직임 이해', detail: '동작의 흐름과 연출 감각' },
        { item: '포트폴리오', detail: '애니메이션적 표현 능력과 독창성' },
      ],
      strategy: ['캐릭터 감정·동작 표현 드로잉을 매일 훈련한다.', '포트폴리오에 스토리보드 또는 짧은 애니메이션 시퀀스를 포함시킨다.', '좋아하는 애니메이션 장면을 모작하며 연출 감각을 키운다.'],
      cautions: ['정적인 그림보다 움직임과 연출 감각이 드러나는 드로잉이 유리하다.'],
    },
  },

  // 동아방송예술대학교 - 웹툰콘텐츠과
  {
    name: '동아방송예술대학교',
    department: '웹툰콘텐츠과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['만화/웹툰 실기'],
    recruitCount: '수시 약 30명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 웹툰 특화 전문대. 실기+포트폴리오 평가.',
    practiceGuide: {
      overview: '웹툰 산업 현장에 특화된 전문대로 실무 중심 교육을 제공한다. 스토리 구성력과 디지털 드로잉 역량을 함께 평가한다.',
      examInfo: { time: '4시간', paper: '지정 용지 또는 디지털', materials: '펜, 마커 또는 타블렛' },
      trends: [
        { year: '2025', topic: '주제어 기반 단편 웹툰 4~6컷 구성' },
        { year: '2024', topic: '캐릭터 설정 + 스토리 전개' },
      ],
      scoring: [
        { item: '스토리텔링', detail: '기승전결 구성과 연출력' },
        { item: '캐릭터 표현', detail: '개성과 감정 표현력' },
        { item: '드로잉', detail: '선 품질과 기초 묘사력' },
        { item: '포트폴리오', detail: '완성된 웹툰 작품 수준' },
      ],
      strategy: ['짧은 웹툰을 꾸준히 완성하는 습관을 들인다.', '네이버·카카오 인기 웹툰의 연출 방식을 분석한다.', '디지털 드로잉 툴(클립스튜디오 등) 사용법을 익혀두면 유리하다.'],
      cautions: ['완성도 없는 스케치 수준의 포트폴리오는 감점 요인이다.'],
    },
  },

  // 동아방송예술대학교 - 애니메이션과
  {
    name: '동아방송예술대학교',
    department: '애니메이션과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['드로잉 실기', '포트폴리오'],
    recruitCount: '수시 약 25명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 방송·영상 중심 애니메이션 전문대.',
    practiceGuide: {
      overview: '방송 콘텐츠 애니메이션 제작에 특화된 전문대다. 캐릭터 표현력과 영상 연출 감각을 평가한다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '펜, 마커, 채색 재료' },
      trends: [
        { year: '2025', topic: '캐릭터 동작 시퀀스 드로잉' },
        { year: '2024', topic: '스토리 기반 장면 연출' },
      ],
      scoring: [
        { item: '캐릭터 드로잉', detail: '인체와 동작 표현력' },
        { item: '연출 감각', detail: '장면 구도와 흐름' },
        { item: '포트폴리오', detail: '애니메이션 관련 창작물 완성도' },
      ],
      strategy: ['캐릭터 동작 드로잉을 반복 훈련한다.', '포트폴리오에 스토리보드를 포함시키면 유리하다.'],
      cautions: ['정적인 일러스트보다 움직임이 느껴지는 드로잉이 더 높이 평가된다.'],
    },
  },

  // 동아방송예술대학교 - 영상콘텐츠과
  {
    name: '동아방송예술대학교',
    department: '영상콘텐츠과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: false,
    practiceSubjects: ['면접', '포트폴리오'],
    recruitCount: '수시 약 30명',
    suneungRatio: '없음',
    practiceRatio: '100% (면접+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 방송영상 특화 전문대. 면접+포트폴리오 평가.',
    practiceGuide: {
      overview: '방송·영상 콘텐츠 제작 실무에 특화된 전문대다. 영상 제작 경험과 콘텐츠 기획력을 평가한다.',
      examInfo: { time: '면접 20분', paper: '해당없음', materials: '영상 포트폴리오 USB 또는 링크 제출' },
      trends: [
        { year: '2025', topic: '자체 제작 영상 or 콘텐츠 기획안 기반 면접' },
        { year: '2024', topic: '유튜브·SNS 콘텐츠 제작 경험 면접' },
      ],
      scoring: [
        { item: '제작 경험', detail: '직접 만든 영상 콘텐츠 수준' },
        { item: '기획력', detail: '콘텐츠 아이디어와 실현 가능성' },
        { item: '지원 동기', detail: '방송·영상 분야에 대한 열정과 방향성' },
      ],
      strategy: ['유튜브, 인스타그램 릴스 등 짧은 영상이라도 직접 만들어 포트폴리오에 포함시킨다.', '자신이 만들고 싶은 콘텐츠 기획안을 구체적으로 준비해 간다.'],
      cautions: ['영상 제작 경험이 전혀 없으면 경쟁에서 불리하다.'],
    },
  },

  // 홍익대학교 세종캠퍼스 - 영상·애니메이션학부
  {
    name: '홍익대학교 세종캠퍼스',
    department: '영상·애니메이션학부',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '수시 53명 / 정시 24명',
    suneungRatio: '없음 (수시, 수능최저 없음) / 수능 60%+서류 40% (정시, 가군)',
    practiceRatio: '없음 (수시: 미술활동보고서+면접 / 정시: 수능+서류)',
    competitionRate: '확인필요',
    note: '실기 없음. [수시] 1단계 학생부교과20%+서류(미술활동보고서)80% → 2단계 서류40%+면접60%, 수능최저 없음. [정시] 1단계 수능100%(4배수) → 2단계 수능60%+서류40%, 가군.',
    practiceGuide: {
      overview: '홍익대 세종캠퍼스 영상·애니메이션학부는 실기고사가 없으며, 미술활동보고서(포트폴리오)와 면접으로 선발합니다. 애니메이션·영상 제작 경험을 담은 포트폴리오와 창작 의도를 논리적으로 설명하는 면접 역량이 합격의 핵심입니다.',
      examInfo: {
        time: '면접 10~15분',
        paper: '해당 없음',
        materials: '미술활동보고서 (포트폴리오, 자율 지참)',
      },
      trends: [
        { year: '2025', topic: '영상/애니메이션 창작 경험 및 표현 의도 / 관심 작품과 영향받은 감독·작가' },
        { year: '2024', topic: '본인 포트폴리오 작품 설명 및 제작 과정 / 영상·애니메이션 트렌드에 대한 견해' },
      ],
      scoring: [
        { item: '전공적합성', detail: '영상·애니메이션 관련 창작 활동 및 탐구 경험' },
        { item: '포트폴리오 완성도', detail: '미술활동보고서에 담긴 창작물의 완성도와 다양성' },
        { item: '창의성·표현력', detail: '독창적인 스토리텔링과 영상적 감각' },
        { item: '발전가능성', detail: '학과 교육과정에 대한 이해와 성장 의지' },
      ],
      strategy: [
        '직접 제작한 단편 애니메이션이나 영상 클립을 포트폴리오에 포함하면 압도적으로 유리합니다.',
        '유튜브, 릴스 등 SNS 채널 운영 경험도 창작 활동으로 어필할 수 있습니다.',
        '좋아하는 애니메이션·영화 감독의 연출 스타일을 분석하고 면접에서 설명할 수 있도록 준비하세요.',
        '정시 지원 시 수능 수학과 탐구 성적이 중요합니다. 수능 준비를 병행하세요.',
      ],
      cautions: [
        '실기가 없다고 방심하지 마세요. 포트폴리오+면접이 사실상 실기 역할을 합니다.',
        '서울캠퍼스와 전형 방식은 동일하지만 학부 구성과 모집 인원이 다릅니다.',
        '미술활동보고서는 결과물보다 창작 과정과 탐구 경험을 풍부하게 담는 것이 중요합니다.',
      ],
    },
  },

  // 홍익대학교 세종캠퍼스 - 게임학부 (게임그래픽디자인전공, 미술계)
  {
    name: '홍익대학교 세종캠퍼스',
    department: '게임학부 (게임그래픽디자인전공)',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '수시 29명 / 정시 13명',
    suneungRatio: '없음 (수시, 수능최저 없음) / 수능 60%+서류 40% (정시, 가군)',
    practiceRatio: '없음 (수시: 미술활동보고서+면접 / 정시: 수능+서류)',
    competitionRate: '확인필요',
    note: '실기 없음. 미술계 전형으로 선발. [수시] 1단계 학생부교과20%+서류(미술활동보고서)80% → 2단계 서류40%+면접60%. [정시] 1단계 수능100%(4배수) → 2단계 수능60%+서류40%, 가군. ※ 게임기획전공(인문계)은 별도 전형.',
    practiceGuide: {
      overview: '홍익대 세종캠퍼스 게임학부 게임그래픽디자인전공(미술계)은 실기고사가 없으며, 미술활동보고서(포트폴리오)와 면접으로 선발합니다. 게임 아트·컨셉아트 창작 경험이 중심 평가 요소입니다.',
      examInfo: {
        time: '면접 10~15분',
        paper: '해당 없음',
        materials: '미술활동보고서 (포트폴리오, 자율 지참)',
      },
      trends: [
        { year: '2025', topic: '게임 아트 관련 창작 경험 및 포트폴리오 작품 설명 / 좋아하는 게임과 아트 스타일 분석' },
        { year: '2024', topic: '게임 그래픽 트렌드에 대한 견해 / 본인 작품의 창작 과정' },
      ],
      scoring: [
        { item: '전공적합성', detail: '게임 그래픽·컨셉아트 관련 창작 활동 경험' },
        { item: '포트폴리오 완성도', detail: '게임 아트 관련 작업물의 완성도와 다양성' },
        { item: '창의성', detail: '독창적인 캐릭터·배경·UI 디자인 역량' },
        { item: '발전가능성', detail: '게임 산업에 대한 이해와 성장 의지' },
      ],
      strategy: [
        '게임 캐릭터, 배경, UI 등 다양한 게임 아트 장르의 작업물을 포트폴리오에 포함하세요.',
        '좋아하는 게임의 아트 스타일을 분석하고 모작·재해석 작업을 통해 이해도를 보여주세요.',
        '디지털 드로잉 툴(Photoshop, Clip Studio, Procreate 등) 활용 능력이 있으면 강점입니다.',
        '게임 기획 경험도 있으면 면접에서 아트+기획 융합 역량으로 어필할 수 있습니다.',
      ],
      cautions: [
        '미술계 전형이므로 미술활동보고서(포트폴리오) 준비가 필수입니다.',
        '게임기획전공(인문계)과 전형이 분리되어 있으니 지원 전공을 정확히 확인하세요.',
        '실기가 없다고 방심하지 마세요. 포트폴리오+면접이 핵심입니다.',
      ],
    },
  },

  // 홍익대학교 세종캠퍼스 - 디자인컨버전스학부
  {
    name: '홍익대학교 세종캠퍼스',
    department: '디자인컨버전스학부',
    region: '충청',
    admissionTypes: ['수시', '정시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11 / 정시 2027.01.04 ~ 01.07',
    hasPractice: false,
    practiceSubjects: [],
    recruitCount: '수시 100명 / 정시 44명',
    suneungRatio: '없음 (수시, 수능최저 없음) / 수능 60%+서류 40% (정시, 가군)',
    practiceRatio: '없음 (수시: 미술활동보고서+면접 / 정시: 수능+서류)',
    competitionRate: '확인필요',
    note: '실기 없음. 세종캠 최대 규모 디자인 학부. [수시] 1단계 학생부교과20%+서류80% → 2단계 서류40%+면접60%. [정시] 1단계 수능100%(4배수) → 2단계 수능60%+서류40%, 가군.',
    practiceGuide: {
      overview: '홍익대 세종캠퍼스 디자인컨버전스학부는 시각·제품·공간·UX 등 다양한 디자인 분야를 융합적으로 교육합니다. 실기고사 없이 미술활동보고서(포트폴리오)와 면접으로 선발하며, 입학 후 세부 전공을 선택합니다.',
      examInfo: {
        time: '면접 10~15분',
        paper: '해당 없음',
        materials: '미술활동보고서 (포트폴리오, 자율 지참)',
      },
      trends: [
        { year: '2025', topic: '"디자인이 사회문제 해결에 기여한 사례" / 본인 포트폴리오 작품 의도 설명' },
        { year: '2024', topic: '영향받은 디자이너와 그 이유 / 디자인 트렌드에 대한 견해' },
      ],
      scoring: [
        { item: '전공적합성', detail: '디자인 관련 활동, 탐구, 창작 경험' },
        { item: '포트폴리오 완성도', detail: '다양한 분야의 디자인 작업물과 기획력' },
        { item: '학업역량', detail: '내신 성적 및 학교생활 충실도' },
        { item: '발전가능성', detail: '디자인적 사고와 문제 해결 능력' },
      ],
      strategy: [
        '시각·제품·UX·공간 등 다양한 디자인 분야에 걸친 폭넓은 포트폴리오를 구성하세요.',
        '디자인 프로세스(문제 정의→리서치→아이디어→결과물)를 포트폴리오에 명확히 담으세요.',
        '학교 수업 내 세특에 디자인 관련 탐구 활동을 기록해두세요.',
        '서울캠퍼스 대비 경쟁이 상대적으로 낮을 수 있으나 홍익대 브랜드로 경쟁력 있는 지원자들이 몰립니다.',
      ],
      cautions: [
        '모집 인원이 수시 100명으로 크지만 그만큼 지원자도 많습니다.',
        '실기 없음이라고 포트폴리오 준비를 소홀히 하면 면접에서 불리합니다.',
        '입학 후 세부 전공 선택이 이루어지므로 특정 분야에 집착하기보다 폭넓은 관심을 보여주세요.',
      ],
    },
  },

  // 계원예술대학교 - 웹툰과
  {
    name: '계원예술대학교',
    department: '웹툰과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['만화/웹툰 실기'],
    recruitCount: '수시 약 30명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 웹툰 특화 전문대. 업계 취업률 상위권.',
    practiceGuide: {
      overview: '계원예대 웹툰과는 업계 취업률이 높은 실무 중심 전문대다. 스토리텔링과 완성된 단편 작품이 핵심 평가 요소다.',
      examInfo: { time: '4시간', paper: '지정 용지 또는 디지털', materials: '펜, 마커 또는 타블렛' },
      trends: [
        { year: '2025', topic: '주제어 기반 단편 웹툰 6컷 구성' },
        { year: '2024', topic: '감정 표현 중심 캐릭터 장면 연출' },
      ],
      scoring: [
        { item: '스토리텔링', detail: '기승전결 구성과 연출력' },
        { item: '캐릭터', detail: '개성 있는 캐릭터 창작력' },
        { item: '드로잉', detail: '선 품질과 인체 기본기' },
        { item: '포트폴리오', detail: '완성된 웹툰 작품 수와 완성도' },
      ],
      strategy: ['매주 단편 웹툰을 완성하는 습관을 들인다.', '포트폴리오는 완성도보다 다양한 장르와 스토리를 담는 것이 유리하다.', '디지털 드로잉 능력이 있으면 포트폴리오 질이 올라간다.'],
      cautions: ['미완성 스케치 포트폴리오는 감점 요인이다.', '실기 당일 스토리를 빠르게 구성하는 능력이 중요하다.'],
    },
  },

  // 계원예술대학교 - 애니메이션과
  {
    name: '계원예술대학교',
    department: '애니메이션과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['드로잉 실기', '포트폴리오'],
    recruitCount: '수시 약 25명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 2D/3D 애니메이션 통합 전문대.',
    practiceGuide: {
      overview: '2D 드로잉 기반 애니메이션과 3D 제작을 통합 교육한다. 캐릭터 표현력과 움직임에 대한 이해가 중요하다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '펜, 마커, 채색 재료' },
      trends: [
        { year: '2025', topic: '캐릭터 감정 변화 동작 드로잉' },
        { year: '2024', topic: '주어진 스토리 기반 장면 연출' },
      ],
      scoring: [
        { item: '캐릭터 드로잉', detail: '표현력과 인체 기본기' },
        { item: '움직임 이해', detail: '동작과 흐름의 자연스러움' },
        { item: '포트폴리오', detail: '애니메이션·드로잉 창작물' },
      ],
      strategy: ['캐릭터 연속 동작 드로잉을 꾸준히 연습한다.', '포트폴리오에 스토리보드나 간단한 플립북을 포함하면 강점이 된다.'],
      cautions: ['3D 툴 경험이 없어도 지원 가능하지만, 드로잉 기본기는 필수다.'],
    },
  },

  // 계원예술대학교 - 영상과
  {
    name: '계원예술대학교',
    department: '영상과',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: false,
    practiceSubjects: ['면접', '포트폴리오'],
    recruitCount: '수시 약 25명',
    suneungRatio: '없음',
    practiceRatio: '100% (면접+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 영상 제작·편집 실무 특화 전문대.',
    practiceGuide: {
      overview: '영상 촬영·편집·연출 실무에 특화된 전문대다. 직접 만든 영상 포트폴리오와 지원 동기가 핵심 평가 요소다.',
      examInfo: { time: '면접 20분', paper: '해당없음', materials: '영상 포트폴리오 USB 또는 링크 제출' },
      trends: [
        { year: '2025', topic: '자체 제작 단편 영상 기반 면접' },
        { year: '2024', topic: '콘텐츠 기획안 + 제작 경험 면접' },
      ],
      scoring: [
        { item: '포트폴리오', detail: '직접 제작한 영상의 수준과 창의성' },
        { item: '지원 동기', detail: '영상에 대한 열정과 방향성' },
        { item: '기획력', detail: '콘텐츠 아이디어와 실행력' },
      ],
      strategy: ['스마트폰으로 단편 영상을 만들어 포트폴리오를 쌓는다.', '프리미어, 다빈치 등 편집 툴을 미리 익혀두면 유리하다.'],
      cautions: ['영상 제작 경험이 없으면 면접에서 불리하므로 반드시 작품을 만들어야 한다.'],
    },
  },

  // 청강문화산업대학교 - 만화콘텐츠스쿨
  {
    name: '청강문화산업대학교',
    department: '만화콘텐츠스쿨',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['만화/웹툰 실기'],
    recruitCount: '수시 약 50명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 웹툰 특화 전문대. 모집 인원 많고 실기 중심.',
    practiceGuide: {
      overview: '청강대 만화콘텐츠스쿨은 웹툰 산업 맞춤형 커리큘럼으로 유명하다. 모집 인원이 많아 진입 장벽이 상대적으로 낮지만 완성도 있는 포트폴리오가 중요하다.',
      examInfo: { time: '4시간', paper: '지정 용지 또는 디지털', materials: '펜, 마커 또는 타블렛' },
      trends: [
        { year: '2025', topic: '주제 기반 단편 웹툰 4~8컷' },
        { year: '2024', topic: '캐릭터 설정 + 장면 연출' },
      ],
      scoring: [
        { item: '스토리텔링', detail: '기승전결 구성과 장면 연출력' },
        { item: '캐릭터', detail: '독창적 캐릭터 창작력' },
        { item: '드로잉', detail: '기본 묘사력과 선 완성도' },
        { item: '포트폴리오', detail: '완성된 웹툰 작품 수준' },
      ],
      strategy: ['단편 웹툰을 꾸준히 완성하며 포트폴리오를 쌓는다.', '네이버·카카오 인기 웹툰 연출 방식을 분석해 자신의 스타일에 적용한다.'],
      cautions: ['모집 인원이 많다고 준비를 소홀히 하면 안 된다. 완성도 있는 작품이 기본이다.'],
    },
  },

  // 청강문화산업대학교 - 애니메이션스쿨
  {
    name: '청강문화산업대학교',
    department: '애니메이션스쿨',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: true,
    practiceSubjects: ['드로잉 실기', '포트폴리오'],
    recruitCount: '수시 약 40명',
    suneungRatio: '없음',
    practiceRatio: '100% (실기+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 2D·3D 애니메이션 특화. 국내 최대 규모 애니메이션 전문대 중 하나.',
    practiceGuide: {
      overview: '청강대 애니메이션스쿨은 국내 최대 규모의 애니메이션 전문 교육기관 중 하나다. 2D 드로잉과 3D 제작 능력을 함께 키운다.',
      examInfo: { time: '4시간', paper: '지정 용지', materials: '펜, 마커, 채색 재료' },
      trends: [
        { year: '2025', topic: '캐릭터 동작·감정 표현 드로잉' },
        { year: '2024', topic: '스토리 기반 장면 연출 드로잉' },
      ],
      scoring: [
        { item: '드로잉', detail: '캐릭터·배경 묘사력' },
        { item: '움직임 이해', detail: '동작 연속성과 자연스러움' },
        { item: '포트폴리오', detail: '애니메이션 관련 창작물 완성도' },
      ],
      strategy: ['캐릭터 연속 동작 드로잉을 반복 훈련한다.', '포트폴리오에 스토리보드나 플립북을 포함시키면 강점이 된다.', '3D 툴 경험이 있으면 포트폴리오에 포함시킨다.'],
      cautions: ['기본 드로잉 실력이 없으면 3D 능력만으로는 합격이 어렵다.'],
    },
  },

  // 청강문화산업대학교 - 영화영상스쿨
  {
    name: '청강문화산업대학교',
    department: '영화영상스쿨',
    region: '경기',
    admissionTypes: ['수시'],
    applicationPeriod: '수시 2026.09.07 ~ 09.11',
    hasPractice: false,
    practiceSubjects: ['면접', '포트폴리오'],
    recruitCount: '수시 약 40명',
    suneungRatio: '없음',
    practiceRatio: '100% (면접+포트폴리오)',
    competitionRate: '확인필요',
    note: '수시 100%. 영화·영상 제작 특화 전문대.',
    practiceGuide: {
      overview: '영화·영상 제작 실무에 특화된 전문대다. 촬영·편집·연출 등 다양한 세부 분야로 구분되며 포트폴리오와 면접으로 선발한다.',
      examInfo: { time: '면접 20분', paper: '해당없음', materials: '영상 포트폴리오 USB 또는 링크' },
      trends: [
        { year: '2025', topic: '자체 제작 단편 영상 기반 면접' },
        { year: '2024', topic: '콘텐츠 기획안 + 촬영/편집 경험 면접' },
      ],
      scoring: [
        { item: '포트폴리오', detail: '직접 제작한 영상 창의성과 완성도' },
        { item: '지원 동기', detail: '영화·영상 분야 열정과 방향성' },
        { item: '기획력', detail: '영상 아이디어와 실행력' },
      ],
      strategy: ['짧은 단편이라도 직접 촬영·편집한 영상을 포트폴리오로 준비한다.', '프리미어, 파이널컷 등 편집 툴을 익혀두면 실습 수업에 유리하다.'],
      cautions: ['영상 제작 경험 없이 면접만으로 합격하기는 어렵다.'],
    },
  },
];
